# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=524)),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
