# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=524)),
            ],
        ),
        migrations.AlterField(
            model_name='workshops',
            name='desc',
            field=models.TextField(max_length=524),
        ),
    ]
